/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyNativeTest */

#ifndef _Included_MyNativeTest
#define _Included_MyNativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyNativeTest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyNativeTest_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     MyNativeTest
 * Method:    summa
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_MyNativeTest_summa
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
